---
title: "celltype_annotation_assignment"
author: "Jay (Chi Lung) Chow"
date: "2024-06-07"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r package_switch}

detach("package:synthspot")
remove.packages("synthspot")


```


# Importing libraries

```{r libraries}

################  Synthspot ################
#install: https://github.com/saeyslab/synthspot


if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
#BiocManager::install("DropletUtils")
library(DropletUtils)

#install.packages("devtools")
library(devtools)
install_local("../synthspot_devbuild_0.1", force = TRUE)
library(synthspot)

#devtools::install_github("saeyslab/synthspot")
#devtools::install_github("jaychowcl/synthspot")
#library(synthspot)
#library(synthvisium)


################  Seurat + Dependencies  ################
#installation: https://satijalab.org/seurat/articles/install_v5

#install.packages('Seurat')
#install.packages("igraph")
##setRepositories(ind = 1:3, addURLs = c('https://satijalab.r-universe.dev', 'https://bnprks.r-universe.dev/'))
##install.packages(c("BPCells", "presto", "glmGamPoi"))
library(Seurat)
library(dplyr)
library(patchwork)


################  Spatial libraries ################
BiocManager::install("SpatialExperiment")
library(SpatialExperiment)

################  Other libraries ################  

################  Set wd  ################  
setwd("/localdisk/home/s2600569/project")
getwd()

```
# Importing datasets

```{r import_datasets, echo=FALSE}

################  Import Datasets ################  
#indata_dir <- dir("data")
# TODO: fit the iterate over a readmtx() and ftp to just use geo ascessions https://github.com/satijalab/seurat/issues/4096

### Grab file names ###
# data_dir <- dir("data/scRNA_wu") 
# data_dir_mtx <- data_dir[grep("mtx", data_dir)]
# data_dir_feat <- data_dir[grep("meta", data_dir)]
# data_dir_cells <- data_dir[grep("barcode", data_dir)]

### Into Seurat Obj ###
in_data.data <- Read10X(data.dir = "~/project/data/scRNA_wu", gene.column=1) # TODO: need to also account for diff gene column. see https://github.com/satijalab/seurat/issues/1388
in_data <- CreateSeuratObject(counts = in_data.data, project = "scRNA_humanbreastcancer", min.cells = 3, min.features = 200)# TODO: ask if need to alter min.cells and min.features
#in_data <- CreateAssayObject(counts = in_data.data, project = "scRNA_humanbreastcancer", min.cells = 3, min.features = 200)

### Add Metadata  ###
meta<- read.csv("data/scRNA_wu/metadata.csv") # TODO: need to also account for diff metadata file
rownames(meta) <- colnames(in_data)
AddMetaData(in_data, meta)

in_data@meta.data$celltype_subset <- meta$celltype_subset

```

#Assign Cells to Clusters with Annotations

```{r cluster_assignment, echo=FALSE}

Idents(in_data) <- meta$celltype_subset
head(Idents(in_data))

```
```{r run_synthspot, echo=FALSE}
# #convert to v3 experiement
# in_data_v3 <- in_data
# in_data_v3[["RNA"]] <- as(object = in_data_v3[["RNA"]], Class = "Assay")

synthetic_visium_data = generate_synthetic_visium(seurat_obj = in_data, 
                                                  dataset_type = "artificial_uniform_distinct", 
                                                  clust_var = "celltype_subset", 
                                                  n_regions = 5, 
                                                  n_spots_min = 5, 
                                                  n_spots_max = 20, 
                                                  visium_mean = 30000, 
                                                  visium_sd = 8000)




```

