---
title: "celltype_annotation_assignment"
author: "Jay (Chi Lung) Chow"
date: "2024-06-07"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r package_switch}

# detach("package:synthspot")
# remove.packages("synthspot")
# 
# library(dplyr)
```


# Importing libraries

```{r libraries}

################  Synthspot ################
#install: https://github.com/saeyslab/synthspot


# if (!require("BiocManager", quietly = TRUE))
#     install.packages("BiocManager")
# BiocManager::install("DropletUtils")
library(DropletUtils)

#install.packages("devtools")
library(devtools)
#install_local("../synthspot_devbuild_0.1", force = TRUE)
library(synthspot)

#devtools::install_github("saeyslab/synthspot")
#devtools::install_github("jaychowcl/synthspot")
#library(synthspot)
#library(synthvisium)


################  Seurat + Dependencies  ################
#installation: https://satijalab.org/seurat/articles/install_v5

# install.packages('Seurat')
# install.packages("igraph")
##setRepositories(ind = 1:3, addURLs = c('https://satijalab.r-universe.dev', 'https://bnprks.r-universe.dev/'))
##install.packages(c("BPCells", "presto", "glmGamPoi"))
library(Seurat)
library(dplyr)
library(patchwork)


################  Spatial libraries ################
#BiocManager::install("SpatialExperiment")
library(SpatialExperiment)

################  Other libraries ################  

################  Set wd  ################  
setwd("/localdisk/home/s2600569/project")
getwd()

```
# Importing datasets

```{r import_datasets, echo=FALSE}

################  Import Datasets ################  
#indata_dir <- dir("data")
# TODO: fit the iterate over a readmtx() and ftp to just use geo ascessions https://github.com/satijalab/seurat/issues/4096

### Grab file names ###
# data_dir <- dir("data/scRNA_wu") 
# data_dir_mtx <- data_dir[grep("mtx", data_dir)]
# data_dir_feat <- data_dir[grep("meta", data_dir)]
# data_dir_cells <- data_dir[grep("barcode", data_dir)]

### Into Seurat Obj ###
in_data.data <- Read10X(data.dir = "~/project/data/scRNA_wu", gene.column=1) # TODO: need to also account for diff gene column. see https://github.com/satijalab/seurat/issues/1388
in_data <- CreateSeuratObject(counts = in_data.data, project = "scRNA_humanbreastcancer", min.cells = 3, min.features = 200)# TODO: ask if need to alter min.cells and min.features
#in_data <- CreateAssayObject(counts = in_data.data, project = "scRNA_humanbreastcancer", min.cells = 3, min.features = 200)

### Add Metadata  ###
meta<- read.csv("data/scRNA_wu/metadata.csv") # TODO: need to also account for diff metadata file
rownames(meta) <- colnames(in_data)
AddMetaData(in_data, meta)

in_data@meta.data$celltype_subset <- meta$celltype_minor # celltype change

```

#Assign Cells to Clusters with Annotations

```{r cluster_assignment, echo=FALSE}

#Idents(in_data) <- meta$celltype_subset
Idents(in_data) <- meta$celltype_minor
head(Idents(in_data))

```
```{r run_synthspot, echo=FALSE}
# #convert to v3 experiement
# in_data_v3 <- in_data
# in_data_v3[["RNA"]] <- as(object = in_data_v3[["RNA"]], Class = "Assay")

synthetic_visium_data = generate_synthetic_visium(seurat_obj = in_data, 
                                                  dataset_type = "artificial_dominant_celltype_diverse", 
                                                  clust_var = "celltype_subset", 
                                                  n_regions = 5, 
                                                  n_spots_min = 10, 
                                                  n_spots_max = 120, 
                                                  visium_mean = 30000, 
                                                  visium_sd = 8000,
                                                  select_celltype = "Endothelial RGS5")


```


```{r assign_coords, echo=FALSE}

region_coords <- read.csv("./data/spot_coords/regions_coords.csv")
rownames(region_coords) <- region_coords$selected_spots.out1
counts <- synthetic_visium_data$counts # extract counts from synthspot

#assign coords to synthspot spots
col_counts <- colnames(counts)
col_regions <- as.vector(region_coords$selected_spots.out1)
choose_counts <- col_counts %in% col_regions
filtered_counts <- counts[, choose_counts] # final counts matrix


#example(read10xVisium, echo = FALSE)

```

```{r build_spatial_obj, echo=FALSE}

spatial_obj <- SpatialExperiment(assay= list(counts = filtered_counts),
                                 colData=region_coords,
                                 spatialCoordsNames = c("X.Coordinate", "Y.Coordinate"))

#export
# saveRDS(spatial_obj, file="spatialExp.rds")
# saveRDS(in_data, file = "seuratObj.rds")

```


```{r testzone, echo=FALSE}
print_celltypes <- table(in_data@meta.data[,"celltype_subset"])
print(print_celltypes)




print("hello")
```







